version: "3"
services:
  postgres:
    container_name: postgresPractice
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bikeShare
      PGDATA: /data/postgres
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres:
