version: "3"
services:
  postgres:
    container_name: postgresPractice
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bikeShare
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: always
  sharing:
    container_name: share_service
    image: shareservice:1.3.2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURSE_PASSWORD: root
      SPRING_DATASOURSE_USERNAME: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bikeShare
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_FLYWAY_ENABLED: true
    depends_on:
      - postgres
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "90:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - sharing

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus