server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/bikeShare
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true